title: International Press book SILI author support
description: TeX related material for the manuscript preparation for the 
             International Press book edited by Si Li
             (SILI)
show_downloads: true
theme: jekyll-theme-tactile
